version: '3'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - mongo